import type { Metadata } from "next";
import { ViewTransitions } from "next-view-transitions";

import "./globals.css";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ViewTransitions>
      <html lang="en">
        <body className={`antialiased`}>
          {children}
          <Toaster richColors />
          <div className="text-neutral-700 absolute right-0 bottom-0 p-3 text-sm">
            © 2024 창체동아리 PACKET
          </div>
        </body>
      </html>
    </ViewTransitions>
  );
}
